alias nfu='cd $HOME/src/KieraKujisawa/nixos-flake-config; sudo nix flake update'
alias nrs='sudo nixos-rebuild switch --flake $HOME/src/KieraKujisawa/nixos-flake-config'
alias hms='home-manager switch --flake $HOME/src/KieraKujisawa/nixos-flake-config#kieram@nixos -b backup'
alias nixw='cd $HOME/src/KieraKujisawa/nixos-flake-config'
alias ncg='sudo nix-collect-garbage'